/* Simscape target specific file.
 * This file is generated for the Simscape network associated with the solver block 'Tractive_System_model/Solver Configuration1'.
 */

#include "ne_ds.h"
#include "Tractive_System_model_2f85d999_0_initer_idae_ds_sys_struct.h"
#include "Tractive_System_model_2f85d999_0_initer_idae_ds_vdf.h"
#include "Tractive_System_model_2f85d999_0_initer_idae_ds.h"
#include "Tractive_System_model_2f85d999_0_initer_idae_ds_externals.h"
#include "Tractive_System_model_2f85d999_0_initer_idae_ds_external_struct.h"
#include "ssc_ml_fun.h"

int32_T Tractive_System_model_2f85d999_0_initer_idae_ds_vdf(const
  NeDynamicSystem *LC, const NeDynamicSystemInput *t1, NeDsMethodOutput *out)
{
  static boolean_T _cg_const_1[2829] = { true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, false, false,
    false, false, true, true, false, false, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true, true, true,
    true, true, true, true, true, true, true, true, true, true, true };

  int32_T i;
  (void)t1;
  (void)LC;
  for (i = 0; i < 2829; i++) {
    out->mVDF.mX[i] = _cg_const_1[i];
  }

  (void)LC;
  (void)out;
  return 0;
}
